# Generated by Django 5.2.7 on 2025-10-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(blank=True, max_length=10)),
                ('released', models.CharField(blank=True, max_length=50)),
                ('runtime', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField(blank=True)),
                ('poster', models.URLField(max_length=500)),
                ('metascore', models.IntegerField(blank=True, null=True)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('imdb_votes', models.CharField(max_length=50)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
