# Generated by Django 5.2.7 on 2025-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvshow',
            options={'ordering': ['-rating', 'title']},
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='votes',
            field=models.CharField(max_length=20),
        ),
    ]
